<?php

declare(strict_types=1);

namespace Medora\Authority\Llms;

use Medora\Authority\Core\Options;
use Medora\Authority\Support\ContentLanguage;
use Medora\Authority\Support\Cache;
use Medora\Authority\Support\Text;
use WP_Post;

if (! defined('ABSPATH')) {
    exit;
}

/**
 * Builds `/llms.txt` and `/llms-full.txt`.
 *
 * The llms.txt convention is a Markdown document at the site root that gives a
 * language model a curated map of the site: what the site is, which pages
 * matter, and what each one covers. `llms.txt` is the index; `llms-full.txt`
 * inlines the content itself so a model can answer without fetching each URL.
 *
 * Both are generated from live content and cached, so they never drift from
 * the site the way a hand-maintained file does.
 */
final class LlmsTxtGenerator
{
    private const CACHE_INDEX = 'llms_txt_index';
    private const CACHE_FULL  = 'llms_txt_full';
    private const CACHE_TTL   = 6 * HOUR_IN_SECONDS;

    /** Keeps llms-full.txt inside a context window a model can actually use. */
    private const FULL_TOKEN_BUDGET = 120000;

    public function __construct(
        private readonly Options $options,
        private readonly Cache $cache,
        private readonly ContentLanguage $language,
    ) {
    }

    public function index(): string
    {
        return $this->cache->remember(self::CACHE_INDEX, self::CACHE_TTL, fn (): string => $this->buildIndex());
    }

    public function full(): string
    {
        return $this->cache->remember(self::CACHE_FULL, self::CACHE_TTL, fn (): string => $this->buildFull());
    }

    public function flush(): void
    {
        $this->cache->forget(self::CACHE_INDEX);
        $this->cache->forget(self::CACHE_FULL);
    }

    private function buildIndex(): string
    {
        $name        = $this->siteName();
        $description = $this->siteDescription();

        $lines = [
            sprintf('# %s', $name),
            '',
            sprintf('> %s', $description),
            '',
            // Stated explicitly: a model that has to infer the language from
            // the sample of titles below will get a mixed-language site wrong,
            // and llms.txt has no other place to say it.
            sprintf('Language: %s', $this->language->tag()),
            '',
        ];

        $notes = $this->options->getString('llms_txt_notes');

        if ($notes !== '') {
            $lines[] = trim($notes);
            $lines[] = '';
        }

        if ($this->options->getString('site_mode') === 'medical') {
            // Stating the review posture explicitly is the single most useful
            // trust signal a health site can give an answer engine.
            $lines[] = '## Editorial standards';
            $lines[] = '';
            $lines[] = 'Health content on this site is written and reviewed by named, credentialed clinicians. '
                . 'Each article records its author, reviewer and last-reviewed date, and cites primary literature where claims are made. '
                . 'Content is informational and does not replace individual medical advice.';
            $lines[] = '';
        }

        foreach ($this->sections() as $heading => $entries) {
            if ($entries === []) {
                continue;
            }

            $lines[] = sprintf('## %s', $heading);
            $lines[] = '';

            foreach ($entries as $entry) {
                $lines[] = sprintf(
                    '- [%s](%s)%s',
                    $this->escapeMarkdown($entry['title']),
                    $entry['url'],
                    $entry['summary'] === '' ? '' : ': ' . $this->escapeMarkdown($entry['summary'])
                );
            }

            $lines[] = '';
        }

        $lines[] = '## Machine-readable resources';
        $lines[] = '';
        $lines[] = sprintf('- [Full content bundle](%s): every page above, inlined as Markdown.', home_url('/llms-full.txt'));
        $lines[] = sprintf('- [AI sitemap](%s): canonical URL set with entity annotations.', home_url('/medora-sitemap.xml'));
        $lines[] = sprintf('- [Knowledge graph](%s): entities and relationships as JSON-LD.', rest_url('medora/v1/graph'));
        $lines[] = '';
        $lines[] = sprintf('<!-- Generated by Medora Authority %s on %s -->', MEDORA_VERSION, gmdate('c'));

        /**
         * Filter the finished llms.txt document.
         *
         * @param string $content
         */
        return (string) apply_filters('medora_llms_txt', implode("\n", $lines));
    }

    private function buildFull(): string
    {
        $lines = [
            sprintf('# %s — full content bundle', $this->siteName()),
            '',
            sprintf('> %s', $this->siteDescription()),
            '',
            sprintf('Generated %s. Source of truth: %s', gmdate('c'), home_url('/')),
            '',
            '---',
            '',
        ];

        $budget    = self::FULL_TOKEN_BUDGET;
        $truncated = 0;

        foreach ($this->sections() as $heading => $entries) {
            foreach ($entries as $entry) {
                $post = get_post($entry['id']);

                if (! $post instanceof WP_Post) {
                    continue;
                }

                $body   = Text::plain($post->post_content);
                $tokens = Text::estimateTokens($body);

                if ($tokens > $budget) {
                    $truncated++;
                    continue;
                }

                $budget -= $tokens;

                $lines[] = sprintf('## %s', $this->escapeMarkdown($entry['title']));
                $lines[] = '';
                $lines[] = sprintf('Source: %s', $entry['url']);
                $lines[] = sprintf('Section: %s', $heading);
                $lines[] = sprintf('Updated: %s', get_post_modified_time('c', true, $post));
                $lines[] = '';
                $lines[] = $body;
                $lines[] = '';
                $lines[] = '---';
                $lines[] = '';
            }
        }

        if ($truncated > 0) {
            $lines[] = sprintf(
                '<!-- %d further page(s) omitted to stay within the context budget. Fetch them individually from llms.txt. -->',
                $truncated
            );
        }

        return (string) apply_filters('medora_llms_full_txt', implode("\n", $lines));
    }

    /**
     * Curated site map, grouped into sections a model can reason about.
     *
     * Ordering is deliberate: pages with a higher authority score come first,
     * so a model reading top-down encounters the strongest content first.
     *
     * @return array<string, list<array{id: int, title: string, url: string, summary: string}>>
     */
    private function sections(): array
    {
        $sections  = [];
        $postTypes = $this->includedPostTypes();

        foreach ($postTypes as $postType) {
            $object = get_post_type_object($postType);

            if ($object === null) {
                continue;
            }

            $posts = get_posts([
                'post_type'        => $postType,
                'post_status'      => 'publish',
                'numberposts'      => (int) apply_filters('medora_llms_txt_per_type', 200, $postType),
                'orderby'          => 'modified',
                'order'            => 'DESC',
                'suppress_filters' => false,
            ]);

            $entries = [];

            foreach ($posts as $post) {
                if ($this->isExcluded($post)) {
                    continue;
                }

                $entries[] = [
                    'id'      => $post->ID,
                    'title'   => get_the_title($post),
                    'url'     => get_permalink($post),
                    'summary' => $this->summaryFor($post),
                ];
            }

            if ($entries !== []) {
                $sections[$object->labels->name] = $entries;
            }
        }

        return apply_filters('medora_llms_txt_sections', $sections);
    }

    /** @return list<string> */
    private function includedPostTypes(): array
    {
        $configured = $this->options->getArray('llms_post_types');

        if ($configured !== []) {
            return array_values(array_filter(array_map('strval', $configured), 'post_type_exists'));
        }

        $public = get_post_types(['public' => true], 'names');
        unset($public['attachment']);

        return array_values($public);
    }

    private function isExcluded(WP_Post $post): bool
    {
        if (get_post_meta($post->ID, '_medora_exclude_llms', true) === '1') {
            return true;
        }

        if (! empty($post->post_password)) {
            return true;
        }

        return (bool) apply_filters('medora_llms_txt_exclude', false, $post);
    }

    private function summaryFor(WP_Post $post): string
    {
        // Prefer the AI summary the Prompt Engine generated; fall back to the
        // hand-written excerpt, then to the opening sentence.
        $summary = (string) get_post_meta($post->ID, '_medora_ai_summary', true);

        if ($summary === '' && $post->post_excerpt !== '') {
            $summary = $post->post_excerpt;
        }

        if ($summary === '') {
            $sentences = Text::sentences($post->post_content);
            $summary   = $sentences[0] ?? '';
        }

        return Text::truncate(Text::plain($summary), 180);
    }

    private function siteName(): string
    {
        $configured = $this->options->getString('organization_name');

        return $configured !== '' ? $configured : (string) get_bloginfo('name');
    }

    private function siteDescription(): string
    {
        $description = $this->options->getString('llms_txt_description');

        if ($description === '') {
            $description = (string) get_bloginfo('description');
        }

        return $description !== ''
            ? $description
            : sprintf(
                /* translators: %s: site name. */
                __('Reference content published by %s.', 'medora-authority'),
                $this->siteName()
            );
    }

    /** Escape the characters that would break a Markdown list item. */
    private function escapeMarkdown(string $value): string
    {
        return str_replace(['[', ']', "\n"], ['\[', '\]', ' '], trim($value));
    }
}
